### ISSUE TITLE
Issue with opam build using the template

### ISSUE THREAD

**Issue by Zimmi48** [coq-community/manifesto#62] opened 2019-04-16 09:15 UTC
There is currently something going on that makes the opam job in math-classes, qarith-stern-brocot, lemma-overloading and aac-tactics fail.

The error looks like this:

```
[ERROR] Command "/usr/bin/git diff --no-ext-diff --quiet" failed:
"/usr/bin/git diff --no-ext-diff --quiet" exited with code 128 "error: object directory /home/coq/.opam/download-cache/git/objects does not exist; check .git/objects/info/alternates."
The command "# Prepare the COQ container
  docker pull ${COQ_IMAGE}
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB_NAME} -w /home/coq/${CONTRIB_NAME} ${COQ_IMAGE}
  docker exec COQ /bin/bash --login -c "
    # This bash script is double-quoted to interpolate Travis CI env vars:
    echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
    export PS4='+ (\$0 @ line \$LINENO) \$ '
    set -ex  # -e = exit on failure; -x = trace for debug
    opam update -y
    opam install -y -j ${NJOBS} --deps-only .
    opam config list
    opam repo list
    opam list
    "
  " failed and exited with 99 during .
```

cc @erikmd: You might be able to understand better than me what's going on.

**Comment by erikmd** [comment] 2019-04-16 10:16
@Zimmi48 thanks for opening this issue; it only affects `coqorg/coq:dev` which now relies on git pinning (`opam pin add -n -y -k git coq "git+https://github.com/coq/coq#${COQ_COMMIT}"`) instead of version pinning (`opam pin add -n -k version coq dev`).

It might be an opam bug, however I've just pushed a workaround that could fix coq-community's CI jobs…
We'll be able to restart one of these jobs once the new `coqorg/coq:dev` image is ready (to check it: monitor https://hub.docker.com/r/coqorg/coq/builds which currently says "Updated 9 hours ago")

**Comment by erikmd** [comment] 2019-04-16 11:55
> We'll be able to restart one of these jobs once the new `coqorg/coq:dev` image is ready.

@Zimmi48 done, so I've relaunched this job:
https://travis-ci.com/coq-community/math-classes/builds/108405793

**Comment by Zimmi48** [comment] 2019-04-16 12:23
That worked, thanks! Do you want to keep the issue open or to close it?

**Comment by erikmd** [comment] 2019-04-16 12:34
I've reported the issue upstream here: ocaml/opam#3828.

But regarding coq-community CI, the issue is resolved with the implemented workaround so I'd say we can close this issue #62 :)

**Closed by erikmd** 2019-04-16 12:34 UTC
