### ISSUE TITLE
Proposal to move project fourcolor to coq-community

### ISSUE THREAD

**Issue by ybertot** [coq-community/manifesto#139] opened 2022-03-09 10:29 UTC
**Project name:** fourcolor

**Initial author(s):** Georges Gonthier

**Current URL:** https://github.com/math-comp/fourcolor

**Kind:** formalization of a mathematical theorem

**License:** CeCILL-B

**Description:** The repository contains a [mechanization](http://www.ams.org/notices/200811/tx081101382p.pdf) of the [Four Color Theorem](https://en.wikipedia.org/wiki/Four_color_theorem)(Appel & Haken, 1976), a landmark result of graph theory.

The formal proof is based on the [Mathematical Components](https://github.com/math-comp/math-comp) library for the [Coq](https://coq.inria.fr/) proof assistant.

**Status:**  maintained

**New maintainer:** @ybertot

**Comment by palmskog** [comment] 2022-03-09 10:37
Thanks for the proposal. This project is very much welcome here. 

However, according to our manifesto, we need permission from Georges to do this move. Ideally @ggonthier would comment on this issue himself and approve of the move to the Coq-community organization. However, @ybertot if you already have permission by email, you could forward that to either @Zimmi48 or me and this would work just as well to proceed.

**Comment by ybertot** [comment] 2022-03-09 11:58
I already have a mail from @ggonthier giving his approval.  If he does not react to your ping, we can exchange this mail.  Should it be part of this discussion?

**Comment by ybertot** [comment] 2022-03-09 12:06
Sorry, I did not read your message correctly.  I just forwarded the permission that I have by email.

**Comment by palmskog** [comment] 2022-03-09 12:12
Thanks, I can confirm that Georges has indeed given his approval for the move to coq-community.

@ybertot please go ahead and transfer the repo to the coq-community organization, whenever convenient.

**Comment by palmskog** [comment] 2022-03-10 14:29
I'm closing this since the repo has been moved to [here](github.com/coq-community/fourcolor) (thanks to Assia). Let's continue any discussions as issues or PRs in the repo.

**Closed by palmskog** 2022-03-10 14:29 UTC
Labels: move-project, coq-library
